# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-29 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hilcor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('measure', models.CharField(max_length=3)),
                ('price_p_u', models.FloatField()),
                ('total_price', models.FloatField()),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hilcor.Product')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaceOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('order_file', models.FileField(upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=10)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField()),
                ('contact', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('request_date', models.DateField()),
                ('answer_date', models.DateField()),
                ('subtotal', models.FloatField()),
                ('iva', models.FloatField()),
                ('total_iva', models.FloatField()),
                ('total', models.FloatField()),
                ('products', models.ManyToManyField(related_name='order_item', through='hilcor.ProductInQuote', to='hilcor.Product')),
            ],
        ),
        migrations.AddField(
            model_name='purchaceorder',
            name='quote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hilcor.Quote'),
        ),
        migrations.AddField(
            model_name='productinquote',
            name='quote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hilcor.Quote'),
        ),
    ]
