# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-29 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hilcor', '0002_auto_20171029_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='products',
        ),
        migrations.AlterField(
            model_name='productinquote',
            name='measure',
            field=models.CharField(choices=[(b'Kg', b'Kilogramos (Kg)')], max_length=3),
        ),
        migrations.AlterField(
            model_name='productinquote',
            name='price_p_u',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='productinquote',
            name='total_price',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='answer_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='iva',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='subtotal',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='total',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='total_iva',
            field=models.FloatField(blank=True),
        ),
    ]
