# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-29 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hilcor', '0003_auto_20171029_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinquote',
            name='price_p_u',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='productinquote',
            name='total_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='quote',
            name='iva',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='quote',
            name='subtotal',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='quote',
            name='total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='quote',
            name='total_iva',
            field=models.FloatField(default=0.0),
        ),
    ]
