# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-29 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hilcor', '0004_auto_20171029_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='comment',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AddField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[(b'P', b'Pendiente'), (b'A', b'Activa'), (b'T', b'Terminada'), (b'C', b'Cancelada')], default=b'P', max_length=3),
        ),
    ]
