# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 01:07
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hilcor', '0006_auto_20171111_2014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaceorder',
            old_name='order_file',
            new_name='po_file',
        ),
        migrations.AlterField(
            model_name='product',
            name='availability',
            field=models.BooleanField(default=False, verbose_name=b'Producto Disponible'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default=b'', verbose_name=b'Descripci\xc3\xb3n'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name=b' Nombre del Producto *'),
        ),
        migrations.AlterField(
            model_name='productinquote',
            name='measure',
            field=models.CharField(choices=[(b'Kg', b'Kilogramos (Kg)')], default=b'Kg', max_length=3, verbose_name=b'Medida'),
        ),
        migrations.AlterField(
            model_name='productinquote',
            name='price_p_u',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0, b'Precio por unidad debe ser mayor a %(limit_value)s')], verbose_name=b'Precio por Unidad de Medida *'),
        ),
        migrations.AlterField(
            model_name='productinquote',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hilcor.Product', verbose_name='products'),
        ),
        migrations.AlterField(
            model_name='productinquote',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name=b'Cantidad * '),
        ),
        migrations.AlterField(
            model_name='productinquote',
            name='total_price',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0, b'Precio total debe ser mayor a %(limit_value)s')], verbose_name=b'Precio Total'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='address',
            field=models.TextField(verbose_name=b'Direcci\xc3\xb3n *'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='answer_date',
            field=models.DateField(null=True, verbose_name=b'Fecha de Respuesta'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='comment',
            field=models.TextField(blank=True, default=b'', verbose_name=b'Comentarios'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='company',
            field=models.CharField(blank=True, max_length=100, verbose_name=b'Empresa'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='contact',
            field=models.CharField(max_length=100, verbose_name=b'Persona de Contacto *'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='email',
            field=models.CharField(max_length=100, verbose_name=b'Correo Electr\xc3\xb3nico *'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='iva',
            field=models.FloatField(default=12, validators=[django.core.validators.MinValueValidator(0.0, b'Precio por unidad debe ser mayor a %(limit_value)s')], verbose_name=b'(%) IVA'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='number',
            field=models.CharField(blank=True, default=b'', max_length=12, verbose_name=b'N\xc3\xbamero'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='phone',
            field=models.CharField(max_length=20, verbose_name=b'Tel\xc3\xa9fono *'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='request_date',
            field=models.DateField(verbose_name=b'Fecha de Solicitud'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[(b'P', b'Pendiente'), (b'A', b'Activo'), (b'E', b'Procesando'), (b'T', b'Terminado'), (b'C', b'Cancelado')], default=b'P', max_length=3, verbose_name=b'Estado'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='subtotal',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0, b'Precio por unidad debe ser mayor a %(limit_value)s')], verbose_name=b'Subtotal'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='total',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0, b'Precio por unidad debe ser mayor a %(limit_value)s')], verbose_name=b'Total a Pagar'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='total_iva',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0, b'Precio por unidad debe ser mayor a %(limit_value)s')], verbose_name=b'Total IVA'),
        ),
    ]
