# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 01:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hilcor', '0007_auto_20171111_2107'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PurchaceOrder',
            new_name='PurchaseOrder',
        ),
    ]
