# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hilcor', '0008_auto_20171111_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_file',
            field=models.FileField(upload_to=b'purchaseorders/', verbose_name=b'Seleccione Archivo de Orden de Compra (PDF) * '),
        ),
    ]
