# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 15:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hilcor', '0009_auto_20171111_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('business_name', models.CharField(max_length=100, verbose_name=b'Raz\xc3\xb3n Social *')),
                ('address', models.TextField(verbose_name=b'Domicilio Fiscal *')),
                ('phone', models.CharField(max_length=20, verbose_name=b'Tel\xc3\xa9fono *')),
                ('rif', models.CharField(max_length=100, verbose_name=b'RIF *')),
                ('quote', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hilcor.Quote')),
            ],
        ),
        migrations.CreateModel(
            name='ProductInInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name=b'Cantidad * ')),
                ('measure', models.CharField(choices=[(b'Kg', b'Kilogramos (Kg)')], default=b'Kg', max_length=3, verbose_name=b'Medida')),
                ('price_p_u', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0, b'Precio por unidad debe ser mayor a %(limit_value)s')], verbose_name=b'Precio por Unidad de Medida *')),
                ('total_price', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0, b'Precio total debe ser mayor a %(limit_value)s')], verbose_name=b'Precio Total')),
                ('code', models.CharField(blank=True, default=b'', max_length=12, verbose_name=b'C\xc3\xb3digo *')),
                ('order_number', models.CharField(blank=True, default=b'', max_length=12, verbose_name=b'N\xc3\xbamero de Orden de Entrega *')),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hilcor.Invoice')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hilcor.Product', verbose_name='products')),
            ],
        ),
    ]
