# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 15:51
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hilcor', '0010_invoice_productininvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='comment',
            field=models.TextField(blank=True, default=b'', verbose_name=b'Comentarios'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='iva',
            field=models.FloatField(default=12, validators=[django.core.validators.MinValueValidator(0.0, b'Precio por unidad debe ser mayor a %(limit_value)s')], verbose_name=b'(%) IVA'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='number',
            field=models.CharField(blank=True, default=b'', max_length=12, verbose_name=b'N\xc3\xbamero'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[(b'P', b'Pendiente'), (b'Pa', b'Pagada'), (b'C', b'Cancelada')], default=b'P', max_length=3, verbose_name=b'Estado'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='subtotal',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0, b'Precio por unidad debe ser mayor a %(limit_value)s')], verbose_name=b'Subtotal'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0, b'Precio por unidad debe ser mayor a %(limit_value)s')], verbose_name=b'Total a Pagar'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_iva',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0, b'Precio por unidad debe ser mayor a %(limit_value)s')], verbose_name=b'Total IVA'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='address',
            field=models.TextField(default=b'', verbose_name=b'Domicilio Fiscal *'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='business_name',
            field=models.CharField(default=b'', max_length=100, verbose_name=b'Raz\xc3\xb3n Social *'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='phone',
            field=models.CharField(default=b'', max_length=20, verbose_name=b'Tel\xc3\xa9fono *'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='rif',
            field=models.CharField(default=b'', max_length=100, verbose_name=b'RIF *'),
        ),
    ]
