# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hilcor', '0013_auto_20171112_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[(b'C', b'Cheque'), (b'T', b'Transferencia'), (b'D', b'Dep\xc3\xb3sito')], default=b'C', max_length=3, verbose_name=b'Tipo de Operaci\xc3\xb3n *'),
        ),
    ]
