# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-03 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hilcor', '0016_auto_20171202_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='deliver_date',
            field=models.DateField(blank=True, null=True, verbose_name=b'Tel\xc3\xa9fono *'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='comment',
            field=models.TextField(blank=True, default=b'\n        1. Deja sin efecto cualquier Cotizaci\xc3\xb3n u Orden de Compra anterior. \n\n        2. Se requiere la recepci\xc3\xb3n de la Orden de Compra para el procesamiento del pedido.\n\n        3. El IVA se aplicar\xc3\xa1 de acuerdo a lo establecido en la G.O. N\xc2\xba 41.239.\n\n        4. Estos precios est\xc3\xa1n sujetos a cambios SIN PREVIO AVISO, de acuerdo a las variaciones en el mercado nacional de la materia prima fundamental (fibra de algod\xc3\xb3n y material de empaque)\n\n        5. La entrega de la mercanc\xc3\xada est\xc3\xa1 sujeta a la verificaci\xc3\xb3n del pago correspondiente.\n\n        6: Solo se aceptan los m\xc3\xa9todos de pago mencionados en esta Cotizaci\xc3\xb3n.\n    ', verbose_name=b'Comentarios'),
        ),
    ]
